
CREATE DATABASE GestionPoloNorte; 
USE GestionPoloNorte; 

CREATE TABLE IF NOT EXISTS PapaNoel(
IDClon INTEGER NOT NULL UNIQUE,
Edad INTEGER NOT NULL,
Residencia CHAR(12) NOT NULL,
PRIMARY KEY (IDClon));


CREATE TABLE IF NOT EXISTS Reno(
IDReno INTEGER NOT NULL UNIQUE,
Nombre CHAR(50) NOT NULL,
Posicion INTEGER NOT NULL,
ComidaFavorita CHAR(255) NOT NULL,
PRIMARY KEY (IDReno));


CREATE TABLE IF NOT EXISTS Trineo(
IDTrineo INTEGER NOT NULL UNIQUE,
Color CHAR(50) NOT NULL,
Capacidad INTEGER NOT NULL,
PRIMARY KEY (IDTrineo));


CREATE TABLE IF NOT EXISTS Yeti(
IDYeti INTEGER NOT NULL UNIQUE,
Nombre CHAR(50) NOT NULL,
Ocupacion CHAR(256) NOT NULL,
PRIMARY KEY (IDYeti));


CREATE TABLE IF NOT EXISTS Elfo(
IDElfo INTEGER NOT NULL UNIQUE,
ColorUniforme CHAR(50) NOT NULL,
Nombre CHAR(50) NOT NULL,
PRIMARY KEY (IDElfo));


CREATE TABLE IF NOT EXISTS Regalos(
IDRegalo INTEGER NOT NULL UNIQUE,
TipoCaja CHAR(50) NOT NULL,
PRIMARY KEY (IDRegalo));


CREATE TABLE IF NOT EXISTS Juguete(
IDJuguete INTEGER NOT NULL UNIQUE,
Cantidad INTEGER NOT NULL,
ColoresDisponibles CHAR(50) NOT NULL,
Descripcion CHAR(255) NOT NULL,
PRIMARY KEY (IDJuguete));


CREATE TABLE IF NOT EXISTS Tiene(
FK_Regalos INTEGER NOT NULL,
FK_Juguete INTEGER NOT NULL,
FOREIGN KEY (FK_Regalos) REFERENCES Regalos(IDRegalo),
FOREIGN KEY (FK_Juguete) REFERENCES Juguete(IDJuguete));


CREATE TABLE IF NOT EXISTS Envuelve(
ColorPapel CHAR(0) ,
FechaEnvio DATE ,
FK_Elfo INTEGER NOT NULL,
FK_Regalos INTEGER NOT NULL,
FOREIGN KEY (FK_Elfo) REFERENCES Elfo(IDElfo),
FOREIGN KEY (FK_Regalos) REFERENCES Regalos(IDRegalo));


CREATE TABLE IF NOT EXISTS Alimenta(
FK_Reno INTEGER NOT NULL,
FK_Elfo INTEGER NOT NULL,
FOREIGN KEY (FK_Reno) REFERENCES Reno(IDReno),
FOREIGN KEY (FK_Elfo) REFERENCES Elfo(IDElfo));


CREATE TABLE IF NOT EXISTS Acaricia(
FK_Reno INTEGER NOT NULL,
FK_PapaNoel INTEGER NOT NULL,
FOREIGN KEY (FK_Reno) REFERENCES Reno(IDReno),
FOREIGN KEY (FK_PapaNoel) REFERENCES PapaNoel(IDClon));


CREATE TABLE IF NOT EXISTS Conduce(
FK_PapaNoel INTEGER NOT NULL,
FK_Trineo INTEGER NOT NULL,
FOREIGN KEY (FK_PapaNoel) REFERENCES PapaNoel(IDClon),
FOREIGN KEY (FK_Trineo) REFERENCES Trineo(IDTrineo));


CREATE TABLE IF NOT EXISTS Repara(
FK_Trineo INTEGER NOT NULL,
FK_Yeti INTEGER NOT NULL,
FOREIGN KEY (FK_Trineo) REFERENCES Trineo(IDTrineo),
FOREIGN KEY (FK_Yeti) REFERENCES Yeti(IDYeti));


CREATE TABLE IF NOT EXISTS Fabrica(
FK_Juguete INTEGER NOT NULL,
FK_Yeti INTEGER NOT NULL,
FOREIGN KEY (FK_Juguete) REFERENCES Juguete(IDJuguete),
FOREIGN KEY (FK_Yeti) REFERENCES Yeti(IDYeti));



