//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.ANHAMMDRM.ANHAMMDRMLenguaje
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "ANHAMMDRM";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"ANHAMMDRM";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID ANHAMMDRMLenguajeDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ANHAMMDRMLenguajeCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID ANHAMMDRMLenguajeExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ANHAMMDRMLenguajeCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewANHAMMDRMLenguajeExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ANHAMMDRMLenguajeCommandSetId), 0x0001);
	
		// Package identifier
		public const string ANHAMMDRMLenguajePackageId = "22f13f68-9463-472c-8e4e-89d8a68ce4e5";
		
		// Editor factory identifier
		public const string ANHAMMDRMLenguajeEditorFactoryId = "d2fa8704-54f5-400c-960b-a2ea0871c66b";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string ANHAMMDRMLenguajeModelExplorerToolWindowId = "03c27185-238a-44b3-80a0-8e7e54815f4c";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace IPS.ANHAMMDRM.ANHAMMDRMLenguaje
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string ANHAMMDRMLenguajeCommandSetId = "2d45887d-f754-4689-8c59-da42652c1c07";
	}
}