//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using VSShell = global::Microsoft.VisualStudio.Shell;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslModeling = global::Microsoft.VisualStudio.Modeling;

namespace IPS.ANHAMMDRM.ANHAMMDRMLenguaje
{
	/// <summary>
	/// This class implements the VS package that integrates this DSL into Visual Studio.
	/// </summary>
	[VSShell::PackageRegistration(RegisterUsing = VSShell::RegistrationMethod.Assembly, UseManagedResourcesOnly = true, AllowsBackgroundLoading = true)]
	[VSShell::ProvideToolWindow(typeof(ANHAMMDRMLenguajeExplorerToolWindow), MultiInstances = false, Style = VSShell::VsDockStyle.Tabbed, Orientation = VSShell::ToolWindowOrientation.Right, Window = "{3AE79031-E1BC-11D0-8F78-00A0C9110057}")]
	[VSShell::ProvideToolWindowVisibility(typeof(ANHAMMDRMLenguajeExplorerToolWindow), Constants.ANHAMMDRMLenguajeEditorFactoryId)]
	[VSShell::ProvideStaticToolboxGroup("@ANHAMMDRMLenguajeToolboxTab;IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Dsl.dll", "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeToolboxTab",
					"@EntidadToolboxItem;IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Dsl.dll", 
					"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EntidadToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Entidad", 
					"@EntidadToolboxBitmap;IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Dsl.dll", 
					0xff00ff,
					Index = 0)]
	[VSShell::ProvideStaticToolboxItem("IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeToolboxTab",
					"@ClaveToolboxItem;IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Dsl.dll", 
					"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ClaveToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Clave", 
					"@ClaveToolboxBitmap;IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Dsl.dll", 
					0xff00ff,
					Index = 1)]
	[VSShell::ProvideStaticToolboxItem("IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeToolboxTab",
					"@AtributoEToolboxItem;IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Dsl.dll", 
					"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.AtributoEToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AtributoE", 
					"@AtributoEToolboxBitmap;IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Dsl.dll", 
					0xff00ff,
					Index = 2)]
	[VSShell::ProvideStaticToolboxItem("IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeToolboxTab",
					"@RelacionToolboxItem;IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Dsl.dll", 
					"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.RelacionToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Relacion", 
					"@RelacionToolboxBitmap;IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Dsl.dll", 
					0xff00ff,
					Index = 3)]
	[VSShell::ProvideStaticToolboxItem("IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeToolboxTab",
					"@AtributoRToolboxItem;IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Dsl.dll", 
					"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.AtributoRToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AtributoR", 
					"@AtributoRToolboxBitmap;IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Dsl.dll", 
					0xff00ff,
					Index = 4)]
	[VSShell::ProvideStaticToolboxItem("IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeToolboxTab",
					"@RestriccionRangoToolboxItem;IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Dsl.dll", 
					"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.RestriccionRangoToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"RestriccionRango", 
					"@RestriccionRangoToolboxBitmap;IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Dsl.dll", 
					0xff00ff,
					Index = 5)]
	[VSShell::ProvideStaticToolboxItem("IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeToolboxTab",
					"@RestriccionEnumToolboxItem;IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Dsl.dll", 
					"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.RestriccionEnumToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"RestriccionEnum", 
					"@RestriccionEnumToolboxBitmap;IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Dsl.dll", 
					0xff00ff,
					Index = 6)]
	[VSShell::ProvideStaticToolboxItem("IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeToolboxTab",
					"@EstiloGrafPortalWebToolToolboxItem;IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Dsl.dll", 
					"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGrafPortalWebToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"EstiloGrafPortalWebTool", 
					"@EstiloGrafPortalWebToolToolboxBitmap;IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Dsl.dll", 
					0xff00ff,
					Index = 7)]
	[VSShell::ProvideStaticToolboxItem("IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeToolboxTab",
					"@EstiloGráficoPaginaWebToolToolboxItem;IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Dsl.dll", 
					"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGráficoPaginaWebToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"EstiloGráficoPaginaWebTool", 
					"@EstiloGráficoPaginaWebToolToolboxBitmap;IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Dsl.dll", 
					0xff00ff,
					Index = 8)]
	[VSShell::ProvideStaticToolboxItem("IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeToolboxTab",
					"@EstiloGraficoCampoDeFormularioToolToolboxItem;IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Dsl.dll", 
					"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoCampoDeFormularioToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"EstiloGraficoCampoDeFormularioTool", 
					"@EstiloGraficoCampoDeFormularioToolToolboxBitmap;IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Dsl.dll", 
					0xff00ff,
					Index = 9)]
	[VSShell::ProvideStaticToolboxGroup("@ANHAMMDRMLenguajeConectoresToolboxTab;IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Dsl.dll", "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeConectoresToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeConectoresToolboxTab",
					"@ConectorDerechaToolboxItem;IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Dsl.dll", 
					"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ConectorDerechaToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ConectorDerecha", 
					"@ConectorDerechaToolboxBitmap;IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Dsl.dll", 
					0xff00ff,
					Index = 10)]
	[VSShell::ProvideStaticToolboxItem("IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeConectoresToolboxTab",
					"@ConectorIzquierdaToolboxItem;IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Dsl.dll", 
					"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ConectorIzquierdaToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ConectorIzquierda", 
					"@ConectorIzquierdaToolboxBitmap;IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Dsl.dll", 
					0xff00ff,
					Index = 11)]
	[VSShell::ProvideEditorFactory(typeof(ANHAMMDRMLenguajeEditorFactory), 103, TrustLevel = VSShellInterop::__VSEDITORTRUSTLEVEL.ETL_AlwaysTrusted)]
	[VSShell::ProvideEditorExtension(typeof(ANHAMMDRMLenguajeEditorFactory), "." + Constants.DesignerFileExtension, 50)]
	[VSShell::ProvideEditorLogicalView(typeof(ANHAMMDRMLenguajeEditorFactory), "{7651A702-06E5-11D1-8EBD-00A0C90F26EA}")] // Designer logical view GUID i.e. VSConstants.LOGVIEWID_Designer
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.CSharpProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.VisualBasicProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::RegisterAsDslToolsEditor]
	[global::System.Runtime.InteropServices.ComVisible(true)]
	[DslShell::ProvideBindingPath]
	[DslShell::ProvideXmlEditorChooserBlockSxSWithXmlEditor(@"ANHAMMDRMLenguaje", typeof(ANHAMMDRMLenguajeEditorFactory))]

	internal abstract partial class ANHAMMDRMLenguajePackageBase : DslShell::AsyncModelingPackage
	{
		protected global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeToolboxHelper toolboxHelper;	
		
		/// <summary>
		/// Initialization method called by the package base class when this package is loaded.
		/// </summary>
		protected async override System.Threading.Tasks.Task InitializeAsync(CancellationToken cancellationToken, IProgress<VSShell.ServiceProgressData> progress)
		{
			await base.InitializeAsync(cancellationToken, progress);

			// Register the editor factory used to create the DSL editor.
			this.RegisterEditorFactory(new ANHAMMDRMLenguajeEditorFactory(this));
			
			// Initialize the toolbox helper
			toolboxHelper = new global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeToolboxHelper(this);

			// Create the command set that handles menu commands provided by this package.
			ANHAMMDRMLenguajeCommandSet commandSet = new ANHAMMDRMLenguajeCommandSet(this);
			await commandSet.InitializeAsync(cancellationToken);
			
			// Create the command set that handles cut/copy/paste commands provided by this package.
			ANHAMMDRMLenguajeClipboardCommandSet clipboardCommandSet = new ANHAMMDRMLenguajeClipboardCommandSet(this);
			await clipboardCommandSet.InitializeAsync(cancellationToken);
			
			// Register the model explorer tool window for this DSL.
			this.AddToolWindow(typeof(ANHAMMDRMLenguajeExplorerToolWindow));

			if (cancellationToken.IsCancellationRequested)
			{
				return;
			}

			await JoinableTaskFactory.SwitchToMainThreadAsync();

			// Initialize Extension Registars
			// this is a partial method call
			this.InitializeExtensions();

			// Add dynamic toolbox items
			await this.SetupDynamicToolboxAsync(cancellationToken);
		}

		/// <summary>
		/// Partial method to initialize ExtensionRegistrars (if any) in the DslPackage
		/// </summary>
		partial void InitializeExtensions();
		
		/// <summary>
		/// Returns any dynamic tool items for the designer
		/// </summary>
		/// <remarks>The default implementation is to return the list of items from the generated toolbox helper.</remarks>
		protected override global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			try
			{
				Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
				return toolboxHelper.CreateToolboxItems();
			}
			catch (global::System.Exception e)
			{
				global::System.Diagnostics.Debug.Fail("Exception thrown during toolbox item creation.  This may result in Package Load Failure:\r\n\r\n" + e);
				throw;
			}
		}
		
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		protected override object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
		
			// Retrieve the specified ToolboxItem from the DSL
			return toolboxHelper.GetToolboxItemData(itemId, format);
		}

		public override VSShellInterop::IVsAsyncToolWindowFactory GetAsyncToolWindowFactory(Guid toolWindowType)
		{
			if (toolWindowType == typeof(ANHAMMDRMLenguajeExplorerToolWindow).GUID)
			{
				return this;
			}

			return base.GetAsyncToolWindowFactory(toolWindowType);
		}
	}
}

//
// Package attributes which may need to change are placed on the partial class below, rather than in the main include file.
//
namespace IPS.ANHAMMDRM.ANHAMMDRMLenguaje
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	[VSShell::ProvideMenuResource("1000.ctmenu", 1)]
	[VSShell::ProvideToolboxItems(1)]
	[global::Microsoft.VisualStudio.TextTemplating.VSHost.ProvideDirectiveProcessor(typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDirectiveProcessor), global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDirectiveProcessor.ANHAMMDRMLenguajeDirectiveProcessorName, "A directive processor that provides access to ANHAMMDRMLenguaje files")]
	[global::System.Runtime.InteropServices.Guid(Constants.ANHAMMDRMLenguajePackageId)]
	internal sealed partial class ANHAMMDRMLenguajePackage : ANHAMMDRMLenguajePackageBase
	{
	}
}