//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDiagram")]

namespace IPS.ANHAMMDRM.ANHAMMDRMLenguaje
{
	/// <summary>
	/// DomainClass ANHAMMDRMLenguajeDiagram
	/// Description for IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDiagram
	/// </summary>
	[DslDesign::DisplayNameResource("IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDiagram.DisplayName", typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDomainModel), "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDiagram.Description", typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDomainModel), "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("51d26f5d-5907-4939-ae85-74c1f65ce3ee")]
	public partial class ANHAMMDRMLenguajeDiagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Diagram styles
		/// <summary>
		/// Initializes style set resources for this shape type
		/// </summary>
		/// <param name="classStyleSet">The style set for this shape class</param>
		protected override void InitializeResources(DslDiagrams::StyleSet classStyleSet)
		{
			base.InitializeResources(classStyleSet);
			
			// Fill brush settings for this shape.
			DslDiagrams::BrushSettings backgroundBrush = new DslDiagrams::BrushSettings();
			backgroundBrush.Color = global::System.Drawing.Color.FromKnownColor(global::System.Drawing.KnownColor.NavajoWhite);
			classStyleSet.OverrideBrush(DslDiagrams::DiagramBrushes.DiagramBackground, backgroundBrush);
		
		}
		#endregion
		#region Auto-placement
		/// <summary>
		/// Indicate that child shapes should added through view fixup should be placed automatically.
		/// </summary>
		public override bool ShouldAutoPlaceChildShapes
		{
			get
			{
				return true;
			}
		}
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		/// <summary>
		/// Called during view fixup to configure the given child element, after it has been created.
		/// </summary>
		/// <remarks>
		/// Custom code for choosing the shapes attached to either end of a connector is called from here.
		/// </remarks>
		protected override void OnChildConfiguring(DslDiagrams::ShapeElement child, bool createdDuringViewFixup)
		{
			DslDiagrams::NodeShape sourceShape;
			DslDiagrams::NodeShape targetShape;
			DslDiagrams::BinaryLinkShape connector = child as DslDiagrams::BinaryLinkShape;
			if(connector == null)
			{
				base.OnChildConfiguring(child, createdDuringViewFixup);
				return;
			}
			this.GetSourceAndTargetForConnector(connector, out sourceShape, out targetShape);
			
			global::System.Diagnostics.Debug.Assert(sourceShape != null && targetShape != null, "Unable to find source and target shapes for connector.");
			connector.Connect(sourceShape, targetShape);
		}
		
		/// <summary>
		/// helper method to find the shapes for either end of a connector, including calling the user's custom code
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		internal void GetSourceAndTargetForConnector(DslDiagrams::BinaryLinkShape connector, out DslDiagrams::NodeShape sourceShape, out DslDiagrams::NodeShape targetShape)
		{
			sourceShape = null;
			targetShape = null;
			
			if (sourceShape == null || targetShape == null)
			{
				DslDiagrams::NodeShape[] endShapes = GetEndShapesForConnector(connector);
				if(sourceShape == null)
				{
					sourceShape = endShapes[0];
				}
				if(targetShape == null)
				{
					targetShape = endShapes[1];
				}
			}
		}
		
		/// <summary>
		/// Helper method to find shapes for either end of a connector by looking for shapes associated with either end of the relationship mapped to the connector.
		/// </summary>
		private DslDiagrams::NodeShape[] GetEndShapesForConnector(DslDiagrams::BinaryLinkShape connector)
		{
			DslModeling::ElementLink link = connector.ModelElement as DslModeling::ElementLink;
			DslDiagrams::NodeShape sourceShape = null, targetShape = null;
			if (link != null)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = link.LinkedElements;
				if (linkedElements.Count == 2)
				{
					DslDiagrams::Diagram currentDiagram = this.Diagram;
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							sourceShape = shape;
							break;
						}
					}
					
					presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							targetShape = shape;
							break;
						}
					}
		
				}
			}
			
			return new DslDiagrams::NodeShape[] { sourceShape, targetShape };
		}
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.AtributoEntidad)
			{
				global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaAtributoE newShape = new global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaAtributoE(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.AtributoRelacion)
			{
				global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaAtributoR newShape = new global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaAtributoR(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Clave)
			{
				global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaClave newShape = new global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaClave(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.RestriccionRango)
			{
				global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaRestriccionRango newShape = new global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaRestriccionRango(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.RestriccionEnum)
			{
				global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaRestriccionEnum newShape = new global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaRestriccionEnum(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Entidad)
			{
				global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaEntidad newShape = new global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaEntidad(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Relacion)
			{
				global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaRelacion newShape = new global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaRelacion(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoPortalWeb)
			{
				global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaEGPortalWeb newShape = new global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaEGPortalWeb(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoPaginaWeb)
			{
				global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaEGPaginaWeb newShape = new global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaEGPaginaWeb(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoCampoDeFormulario)
			{
				global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaEGCampoDeFormulario newShape = new global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaEGCampoDeFormulario(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EntidadReferencesRelacionedI)
			{
				global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ConectorIzquierda newShape = new global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ConectorIzquierda(this.Partition);
				return newShape;
			}
			if(element is global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EntidadReferencesRelacionedD)
			{
				global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ConectorDerecha newShape = new global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ConectorDerecha(this.Partition);
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
			global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaEntidad.DecoratorsInitialized += MetaforaEntidadDecoratorMap.OnDecoratorsInitialized;
			global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaClave.DecoratorsInitialized += MetaforaClaveDecoratorMap.OnDecoratorsInitialized;
			global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaAtributoE.DecoratorsInitialized += MetaforaAtributoEDecoratorMap.OnDecoratorsInitialized;
			global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaRelacion.DecoratorsInitialized += MetaforaRelacionDecoratorMap.OnDecoratorsInitialized;
			global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaAtributoR.DecoratorsInitialized += MetaforaAtributoRDecoratorMap.OnDecoratorsInitialized;
			global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaRestriccionRango.DecoratorsInitialized += MetaforaRestriccionRangoDecoratorMap.OnDecoratorsInitialized;
			global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaRestriccionEnum.DecoratorsInitialized += MetaforaRestriccionEnumDecoratorMap.OnDecoratorsInitialized;
			global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaEGPortalWeb.DecoratorsInitialized += MetaforaEGPortalWebDecoratorMap.OnDecoratorsInitialized;
			global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaEGPaginaWeb.DecoratorsInitialized += MetaforaEGPaginaWebDecoratorMap.OnDecoratorsInitialized;
			global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.MetaforaEGCampoDeFormulario.DecoratorsInitialized += MetaforaEGCampoDeFormularioDecoratorMap.OnDecoratorsInitialized;
			global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ConectorIzquierda.DecoratorsInitialized += ConectorIzquierdaDecoratorMap.OnDecoratorsInitialized;
			global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ConectorDerecha.DecoratorsInitialized += ConectorDerechaDecoratorMap.OnDecoratorsInitialized;
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaEntidad.
		/// </summary>
		internal static partial class MetaforaEntidadDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaEntidad.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Entidad.nombreEntidadDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "entidad").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaClave.
		/// </summary>
		internal static partial class MetaforaClaveDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaClave.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Atributo.nombreAtributoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "clave").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaAtributoE.
		/// </summary>
		internal static partial class MetaforaAtributoEDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaAtributoE.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Atributo.nombreAtributoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "atributoE").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Atributo.nameTipoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreTipoTextDec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Atributo.longitudDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "longitudEDec").AssociateValueWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Atributo.tipoDatosDomainPropertyId);
				propertyInfo.FilteringValues.Add("Alfanumerico");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "longitudEDec").AssociateVisibilityWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.AtributoNormal.admiteNuloDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "notNullDec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.AtributoNormal.uniqueDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "unicoDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaRelacion.
		/// </summary>
		internal static partial class MetaforaRelacionDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaRelacion.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Relacion.nombreRelacionDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "relacion").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaAtributoR.
		/// </summary>
		internal static partial class MetaforaAtributoRDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaAtributoR.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Atributo.nombreAtributoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "atributoR").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Atributo.nameTipoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreTipoTex").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Atributo.longitudDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "longitudRDec").AssociateValueWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Atributo.tipoDatosDomainPropertyId);
				propertyInfo.FilteringValues.Add("Alfanumerico");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "longitudRDec").AssociateVisibilityWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.AtributoNormal.admiteNuloDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "notNuloDec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.AtributoNormal.uniqueDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "unicoRDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaRestriccionRango.
		/// </summary>
		internal static partial class MetaforaRestriccionRangoDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaRestriccionRango.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.RestriccionRango.valorMaximoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "valorMax").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.RestriccionRango.valorMinimoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "valorMin").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaRestriccionEnum.
		/// </summary>
		internal static partial class MetaforaRestriccionEnumDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaRestriccionEnum.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.RestriccionEnum.tiposRestriccionDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "tiposDeDatos").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaEGPortalWeb.
		/// </summary>
		internal static partial class MetaforaEGPortalWebDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaEGPortalWeb.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoPortalWeb.alineacionTextoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "alineacionDelTexto").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoPortalWeb.colorFondoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "colorDeFondo").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoPortalWeb.colorTextoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "colorDelTexto").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoPortalWeb.tamañoTextoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "tamañoDelTexto").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoPortalWeb.textoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "textoDec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoPortalWeb.tipografiaTextoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "tipografiaDelTexto").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaEGPaginaWeb.
		/// </summary>
		internal static partial class MetaforaEGPaginaWebDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaEGPaginaWeb.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoPaginaWeb.alineacionDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "alineacionDec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoPaginaWeb.colorDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "colorDec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoPaginaWeb.tamañoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "tamañoDec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoPaginaWeb.tipografiaDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "tipografiaDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaEGCampoDeFormulario.
		/// </summary>
		internal static partial class MetaforaEGCampoDeFormularioDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaEGCampoDeFormulario.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoCampoDeFormulario.alineacionDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "alineacionCF").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoCampoDeFormulario.colorDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "colorCF").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoCampoDeFormulario.formatoDeVisualizacionDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "formatoDeVisualizaciónCF").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoCampoDeFormulario.tamañoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "tamañoCF").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoCampoDeFormulario.tipografiaDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "tipografiaCF").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ConectorIzquierda.
		/// </summary>
		internal static partial class ConectorIzquierdaDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ConectorIzquierda.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EntidadReferencesRelacionedI.cardinalidadIMaxDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "cardinalidadIzquierdaMax").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EntidadReferencesRelacionedI.cardinalidadIMinDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "cardinalidadIzquierdaMin").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ConectorDerecha.
		/// </summary>
		internal static partial class ConectorDerechaDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ConectorDerecha.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EntidadReferencesRelacionedD.cardinalidadDMaxDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "cardinalidadDerechaMax").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EntidadReferencesRelacionedD.cardinalidadDMinDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "cardinalidadDerechaMin").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		#endregion
		
		#region Connect actions
		private bool changingMouseAction;
		private global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ConectorDerechaConnectAction conectorDerechaConnectAction;
		private global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ConectorIzquierdaConnectAction conectorIzquierdaConnectAction;
		/// <summary>
		/// Virtual method to provide a filter when to select the mouse action
		/// </summary>
		/// <param name="activeView">Currently active view</param>
		/// <param name="filter">filter string used to filter the toolbox items</param>
		protected virtual bool SelectedToolboxItemSupportsFilterString(DslDiagrams::DiagramView activeView, string filter)
		{
			return activeView.SelectedToolboxItemSupportsFilterString(filter);
		}
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DslDiagrams::DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new global::System.ArgumentNullException("pointArgs");
		
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
			if(activeView != null)
			{
				DslDiagrams::MouseAction action = null;
				if (SelectedToolboxItemSupportsFilterString(activeView, global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeToolboxHelper.ConectorDerechaFilterString))
				{
					if (this.conectorDerechaConnectAction == null)
					{
						this.conectorDerechaConnectAction = new global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ConectorDerechaConnectAction(this);
						this.conectorDerechaConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.conectorDerechaConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeToolboxHelper.ConectorIzquierdaFilterString))
				{
					if (this.conectorIzquierdaConnectAction == null)
					{
						this.conectorIzquierdaConnectAction = new global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ConectorIzquierdaConnectAction(this);
						this.conectorIzquierdaConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.conectorIzquierdaConnectAction;
				} 
				else
				{
					action = null;
				}
				
				if (pointArgs.DiagramClientView.ActiveMouseAction != action)
				{
					try
					{
						this.changingMouseAction = true;
						pointArgs.DiagramClientView.ActiveMouseAction = action;
					}
					finally
					{
						this.changingMouseAction = false;
					}
				}
			}
		}
		
		/// <summary>
		/// Snap toolbox selection back to regular pointer after using a custom connect action.
		/// </summary>
		private void OnConnectActionDeactivated(object sender, DslDiagrams::DiagramEventArgs e)
		{
			OnMouseActionDeactivated();
		}
		
		/// <summary>
		/// Overridable method to manage the mouse deactivation. The default implementation snap stoolbox selection back to regular pointer 
		/// after using a custom connect action.
		/// </summary>
		protected virtual void OnMouseActionDeactivated()
		{
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
		
			if (activeView != null && activeView.Toolbox != null)
			{
				// If we're not changing mouse action due to changing toolbox selection change,
				// reset toolbox selection.
				if (!this.changingMouseAction)
				{
					activeView.Toolbox.SelectedToolboxItemUsed();
				}
			}
		}
		#endregion
		
		/// <summary>
		/// Dispose of connect actions.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if(disposing)
				{
					if(this.conectorDerechaConnectAction != null)
					{
						this.conectorDerechaConnectAction.Dispose();
						this.conectorDerechaConnectAction = null;
					}
					if(this.conectorIzquierdaConnectAction != null)
					{
						this.conectorIzquierdaConnectAction.Dispose();
						this.conectorIzquierdaConnectAction = null;
					}
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		#region Constructors, domain class Id
	
		/// <summary>
		/// ANHAMMDRMLenguajeDiagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x51d26f5d, 0x5907, 0x4939, 0xae, 0x85, 0x74, 0xc1, 0xf6, 0x5c, 0xe3, 0xee);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public ANHAMMDRMLenguajeDiagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public ANHAMMDRMLenguajeDiagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace IPS.ANHAMMDRM.ANHAMMDRMLenguaje
{
	
		/// <summary>
		/// Double derived implementation for the rule that initiates view fixup when an element that has an associated shape is added to the model.
		/// This now enables the DSL author to everride the SkipFixUp() method 
		/// </summary>
		internal partial class FixUpDiagramBase : DslModeling::AddRule
		{
			protected virtual bool SkipFixup(DslModeling::ModelElement childElement)
			{
				return childElement.IsDeleted;
			}
		}
	
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.AtributoEntidad), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.AtributoRelacion), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Clave), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.RestriccionRango), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.RestriccionEnum), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Entidad), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Relacion), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoPortalWeb), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoPaginaWeb), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoCampoDeFormulario), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EntidadReferencesRelacionedI), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EntidadReferencesRelacionedD), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : FixUpDiagramBase
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (this.SkipFixup(childElement))
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is DslModeling::ElementLink)
				{
					parentElement = GetParentForRelationship((DslModeling::ElementLink)childElement);
				} else
				if(childElement is global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.AtributoEntidad)
				{
					parentElement = GetParentForAtributoEntidad((global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.AtributoEntidad)childElement);
				} else
				if(childElement is global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.AtributoRelacion)
				{
					parentElement = GetParentForAtributoRelacion((global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.AtributoRelacion)childElement);
				} else
				if(childElement is global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Clave)
				{
					parentElement = GetParentForClave((global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Clave)childElement);
				} else
				if(childElement is global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.RestriccionRango)
				{
					// Method:
					// private Microsoft.VisualStudio.Modeling.ModelElement GetParentForRestriccionRango(RestriccionRango childElement)
					// {
					// }
					// must be implemented in a partial class of IPS.ANHAMMDRM.ANHAMMDRMLenguaje.FixUpDiagram.  Given a child element,
					// this method should return the parent model element that is associated with the shape or diagram that will be the parent 
					// of the shape created for this child.  If no shape should be created, the method should return null.
					parentElement = GetParentForRestriccionRango((global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.RestriccionRango)childElement);
				} else
				if(childElement is global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.RestriccionEnum)
				{
					// Method:
					// private Microsoft.VisualStudio.Modeling.ModelElement GetParentForRestriccionEnum(RestriccionEnum childElement)
					// {
					// }
					// must be implemented in a partial class of IPS.ANHAMMDRM.ANHAMMDRMLenguaje.FixUpDiagram.  Given a child element,
					// this method should return the parent model element that is associated with the shape or diagram that will be the parent 
					// of the shape created for this child.  If no shape should be created, the method should return null.
					parentElement = GetParentForRestriccionEnum((global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.RestriccionEnum)childElement);
				} else
				if(childElement is global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Entidad)
				{
					parentElement = GetParentForEntidad((global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Entidad)childElement);
				} else
				if(childElement is global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Relacion)
				{
					parentElement = GetParentForRelacion((global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Relacion)childElement);
				} else
				if(childElement is global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoPortalWeb)
				{
					parentElement = GetParentForEstiloGraficoPortalWeb((global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoPortalWeb)childElement);
				} else
				if(childElement is global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoPaginaWeb)
				{
					parentElement = GetParentForEstiloGraficoPaginaWeb((global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoPaginaWeb)childElement);
				} else
				if(childElement is global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoCampoDeFormulario)
				{
					parentElement = GetParentForEstiloGraficoCampoDeFormulario((global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoCampoDeFormulario)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Tapiz GetParentForEntidad( global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Entidad root )
			{
				// Segments 0 and 1
				global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Tapiz result = root.Tapiz;
				if ( result == null ) return null;
				return result;
			}
			public static global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Tapiz GetParentForClave( global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Clave root )
			{
				// Segments 0 and 1
				global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Entidad root2 = root.Entidad;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Tapiz result = root2.Tapiz;
				if ( result == null ) return null;
				return result;
			}
			public static global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Tapiz GetParentForAtributoEntidad( global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.AtributoEntidad root )
			{
				// Segments 0 and 1
				global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Entidad root2 = root.Entidad;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Tapiz result = root2.Tapiz;
				if ( result == null ) return null;
				return result;
			}
			public static global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Tapiz GetParentForRelacion( global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Relacion root )
			{
				// Segments 0 and 1
				global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Tapiz result = root.Tapiz;
				if ( result == null ) return null;
				return result;
			}
			public static global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Tapiz GetParentForAtributoRelacion( global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.AtributoRelacion root )
			{
				// Segments 0 and 1
				global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Relacion root2 = root.Relacion;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Tapiz result = root2.Tapiz;
				if ( result == null ) return null;
				return result;
			}
			public static global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Tapiz GetParentForEstiloGraficoPortalWeb( global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoPortalWeb root )
			{
				// Segments 0 and 1
				global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Tapiz result = root.Tapiz;
				if ( result == null ) return null;
				return result;
			}
			public static global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Tapiz GetParentForEstiloGraficoPaginaWeb( global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoPaginaWeb root )
			{
				// Segments 0 and 1
				global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Tapiz result = root.Tapiz;
				if ( result == null ) return null;
				return result;
			}
			public static global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Tapiz GetParentForEstiloGraficoCampoDeFormulario( global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoCampoDeFormulario root )
			{
				// Segments 0 and 1
				global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Tapiz result = root.Tapiz;
				if ( result == null ) return null;
				return result;
			}
			private static DslModeling::ModelElement GetParentForRelationship(DslModeling::ElementLink elementLink)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = elementLink.LinkedElements;
	
				if (linkedElements.Count == 2)
				{
					DslDiagrams::ShapeElement sourceShape = linkedElements[0] as DslDiagrams::ShapeElement;
					DslDiagrams::ShapeElement targetShape = linkedElements[1] as DslDiagrams::ShapeElement;
	
					if(sourceShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								sourceShape = shape;
								break;
							}
						}
					}
					
					if(targetShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								targetShape = shape;
								break;
							}
						}
					}
					
					if(sourceShape == null || targetShape == null)
					{
						global::System.Diagnostics.Debug.Fail("Unable to find source and/or target shape for view fixup.");
						return null;
					}
	
					DslDiagrams::ShapeElement sourceParent = sourceShape.ParentShape;
					DslDiagrams::ShapeElement targetParent = targetShape.ParentShape;
	
					while (sourceParent != targetParent && sourceParent != null)
					{
						DslDiagrams::ShapeElement curParent = targetParent;
						while (sourceParent != curParent && curParent != null)
						{
							curParent = curParent.ParentShape;
						}
	
						if(sourceParent == curParent)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					while (sourceParent != null)
					{
						// ensure that the parent can parent connectors (i.e., a diagram or a swimlane).
						if(sourceParent is DslDiagrams::Diagram || sourceParent is DslDiagrams::SwimlaneShape)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					global::System.Diagnostics.Debug.Assert(sourceParent != null && sourceParent.ModelElement != null, "Unable to find common parent for view fixup.");
					return sourceParent.ModelElement;
				}
	
				return null;
			}
		}
		
	
		/// <summary>
		/// A rule which fires when data mapped to outer text decorators has changed,
		/// so we can update the decorator host's bounds.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EntidadReferencesRelacionedI), InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EntidadReferencesRelacionedD), InitiallyDisabled=true)]
		internal sealed class DecoratorPropertyChanged : DslModeling::ChangeRule
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Justification = "Generated code.")]
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
				
				if (e.DomainProperty.Id == global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EntidadReferencesRelacionedI.cardinalidadIMaxDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ConectorIzquierda.FindConectorIzquierdaDecorator("cardinalidadIzquierdaMax");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EntidadReferencesRelacionedI.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EntidadReferencesRelacionedI.cardinalidadIMinDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ConectorIzquierda.FindConectorIzquierdaDecorator("cardinalidadIzquierdaMin");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EntidadReferencesRelacionedI.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EntidadReferencesRelacionedD.cardinalidadDMaxDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ConectorDerecha.FindConectorDerechaDecorator("cardinalidadDerechaMax");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EntidadReferencesRelacionedD.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EntidadReferencesRelacionedD.cardinalidadDMinDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ConectorDerecha.FindConectorDerechaDecorator("cardinalidadDerechaMin");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EntidadReferencesRelacionedD.DomainClassId);
					}
				}
			}
		}
	
		/// <summary>
		/// Reroute a connector when the role players of its underlying relationship change
		/// </summary>
		[DslModeling::RuleOn(typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EntidadReferencesRelacionedI), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EntidadReferencesRelacionedD), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed class ConnectorRolePlayerChanged : DslModeling::RolePlayerChangeRule
		{
			/// <summary>
			/// Reroute a connector when the role players of its underlying relationship change
			/// </summary>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				if (e == null) throw new global::System.ArgumentNullException("e");
	
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslDiagrams::PresentationViewsSubject> connectorLinks = DslDiagrams::PresentationViewsSubject.GetLinksToPresentation(e.ElementLink);
				foreach (DslDiagrams::PresentationViewsSubject connectorLink in connectorLinks)
				{
					// Fix up any binary link shapes attached to the element link.
					DslDiagrams::BinaryLinkShape linkShape = connectorLink.Presentation as DslDiagrams::BinaryLinkShape;
					if (linkShape != null)
					{
						global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDiagram diagram = linkShape.Diagram as global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDiagram;
						if (diagram != null)
						{
							if (e.NewRolePlayer != null)
							{
								DslDiagrams::NodeShape fromShape;
								DslDiagrams::NodeShape toShape;
								diagram.GetSourceAndTargetForConnector(linkShape, out fromShape, out toShape);
								if (fromShape != null && toShape != null)
								{
									if (!object.Equals(fromShape, linkShape.FromShape))
									{
										linkShape.FromShape = fromShape;
									}
									if (!object.Equals(linkShape.ToShape, toShape))
									{
										linkShape.ToShape = toShape;
									}
								}
								else
								{
									// delete the connector if we cannot find an appropriate target shape.
									linkShape.Delete();
								}
							}
							else
							{
								// delete the connector if the new role player is null.
								linkShape.Delete();
							}
						}
					}
				}
			}
		}
	}
