//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace IPS.ANHAMMDRM.ANHAMMDRMLenguaje
{
	/// <summary>
	/// DomainModel ANHAMMDRMLenguajeDomainModel
	/// Description for IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguaje
	/// </summary>
	[DslDesign::DisplayNameResource("IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDomainModel.DisplayName", typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDomainModel), "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDomainModel.Description", typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDomainModel), "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("fb91d1ad-9eae-44d7-98b1-1b6ad29e98c2")]
	public partial class ANHAMMDRMLenguajeDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// ANHAMMDRMLenguajeDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0xfb91d1ad, 0x9eae, 0x44d7, 0x98, 0xb1, 0x1b, 0x6a, 0xd2, 0x9e, 0x98, 0xc2);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public ANHAMMDRMLenguajeDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(Tapiz),
				typeof(Entidad),
				typeof(Atributo),
				typeof(Clave),
				typeof(AtributoEntidad),
				typeof(Relacion),
				typeof(AtributoRelacion),
				typeof(Restriccion),
				typeof(RestriccionRango),
				typeof(RestriccionEnum),
				typeof(EstiloGraficoPortalWeb),
				typeof(EstiloGraficoPaginaWeb),
				typeof(EstiloGraficoCampoDeFormulario),
				typeof(AtributoNormal),
				typeof(TapizHasEntidad),
				typeof(EntidadHasClave),
				typeof(EntidadHasAtributoEntidad),
				typeof(EntidadReferencesRelacionedI),
				typeof(RelacionHasAtributoRelacioned),
				typeof(EntidadReferencesRelacionedD),
				typeof(TapizHasRelacioned),
				typeof(TapizHasEstiloGraficoPortalWebbed),
				typeof(TapizHasEstiloGraficoPaginaWebbed),
				typeof(TapizHasEstiloGraficoCampoDeFormularios),
				typeof(AtributoNormalHasRestriccioned),
				typeof(ANHAMMDRMLenguajeDiagram),
				typeof(ConectorDerecha),
				typeof(ConectorIzquierda),
				typeof(MetaforaEntidad),
				typeof(MetaforaClave),
				typeof(MetaforaAtributoE),
				typeof(MetaforaRelacion),
				typeof(MetaforaAtributoR),
				typeof(MetaforaRestriccionRango),
				typeof(MetaforaRestriccionEnum),
				typeof(MetaforaEGPortalWeb),
				typeof(MetaforaEGPaginaWeb),
				typeof(MetaforaEGCampoDeFormulario),
				typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.FixUpDiagram),
				typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.DecoratorPropertyChanged),
				typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ConnectorRolePlayerChanged),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(Tapiz), "solucionTapiz", Tapiz.solucionTapizDomainPropertyId, typeof(Tapiz.solucionTapizPropertyHandler)),
				new DomainMemberInfo(typeof(Entidad), "nombreEntidad", Entidad.nombreEntidadDomainPropertyId, typeof(Entidad.nombreEntidadPropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "nombreAtributo", Atributo.nombreAtributoDomainPropertyId, typeof(Atributo.nombreAtributoPropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "nameTipo", Atributo.nameTipoDomainPropertyId, typeof(Atributo.nameTipoPropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "longitud", Atributo.longitudDomainPropertyId, typeof(Atributo.longitudPropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "tipoDatos", Atributo.tipoDatosDomainPropertyId, typeof(Atributo.tipoDatosPropertyHandler)),
				new DomainMemberInfo(typeof(Relacion), "nombreRelacion", Relacion.nombreRelacionDomainPropertyId, typeof(Relacion.nombreRelacionPropertyHandler)),
				new DomainMemberInfo(typeof(RestriccionRango), "valorMinimo", RestriccionRango.valorMinimoDomainPropertyId, typeof(RestriccionRango.valorMinimoPropertyHandler)),
				new DomainMemberInfo(typeof(RestriccionRango), "valorMaximo", RestriccionRango.valorMaximoDomainPropertyId, typeof(RestriccionRango.valorMaximoPropertyHandler)),
				new DomainMemberInfo(typeof(RestriccionEnum), "tiposRestriccion", RestriccionEnum.tiposRestriccionDomainPropertyId, typeof(RestriccionEnum.tiposRestriccionPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloGraficoPortalWeb), "colorFondo", EstiloGraficoPortalWeb.colorFondoDomainPropertyId, typeof(EstiloGraficoPortalWeb.colorFondoPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloGraficoPortalWeb), "texto", EstiloGraficoPortalWeb.textoDomainPropertyId, typeof(EstiloGraficoPortalWeb.textoPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloGraficoPortalWeb), "colorTexto", EstiloGraficoPortalWeb.colorTextoDomainPropertyId, typeof(EstiloGraficoPortalWeb.colorTextoPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloGraficoPortalWeb), "tamañoTexto", EstiloGraficoPortalWeb.tamañoTextoDomainPropertyId, typeof(EstiloGraficoPortalWeb.tamañoTextoPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloGraficoPortalWeb), "alineacionTexto", EstiloGraficoPortalWeb.alineacionTextoDomainPropertyId, typeof(EstiloGraficoPortalWeb.alineacionTextoPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloGraficoPortalWeb), "tipografiaTexto", EstiloGraficoPortalWeb.tipografiaTextoDomainPropertyId, typeof(EstiloGraficoPortalWeb.tipografiaTextoPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloGraficoPaginaWeb), "color", EstiloGraficoPaginaWeb.colorDomainPropertyId, typeof(EstiloGraficoPaginaWeb.colorPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloGraficoPaginaWeb), "tamaño", EstiloGraficoPaginaWeb.tamañoDomainPropertyId, typeof(EstiloGraficoPaginaWeb.tamañoPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloGraficoPaginaWeb), "alineacion", EstiloGraficoPaginaWeb.alineacionDomainPropertyId, typeof(EstiloGraficoPaginaWeb.alineacionPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloGraficoPaginaWeb), "tipografia", EstiloGraficoPaginaWeb.tipografiaDomainPropertyId, typeof(EstiloGraficoPaginaWeb.tipografiaPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloGraficoCampoDeFormulario), "color", EstiloGraficoCampoDeFormulario.colorDomainPropertyId, typeof(EstiloGraficoCampoDeFormulario.colorPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloGraficoCampoDeFormulario), "tamaño", EstiloGraficoCampoDeFormulario.tamañoDomainPropertyId, typeof(EstiloGraficoCampoDeFormulario.tamañoPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloGraficoCampoDeFormulario), "alineacion", EstiloGraficoCampoDeFormulario.alineacionDomainPropertyId, typeof(EstiloGraficoCampoDeFormulario.alineacionPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloGraficoCampoDeFormulario), "tipografia", EstiloGraficoCampoDeFormulario.tipografiaDomainPropertyId, typeof(EstiloGraficoCampoDeFormulario.tipografiaPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloGraficoCampoDeFormulario), "formatoDeVisualizacion", EstiloGraficoCampoDeFormulario.formatoDeVisualizacionDomainPropertyId, typeof(EstiloGraficoCampoDeFormulario.formatoDeVisualizacionPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoNormal), "admiteNulo", AtributoNormal.admiteNuloDomainPropertyId, typeof(AtributoNormal.admiteNuloPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoNormal), "unique", AtributoNormal.uniqueDomainPropertyId, typeof(AtributoNormal.uniquePropertyHandler)),
				new DomainMemberInfo(typeof(EntidadReferencesRelacionedI), "cardinalidadIMin", EntidadReferencesRelacionedI.cardinalidadIMinDomainPropertyId, typeof(EntidadReferencesRelacionedI.cardinalidadIMinPropertyHandler)),
				new DomainMemberInfo(typeof(EntidadReferencesRelacionedI), "cardinalidadIMax", EntidadReferencesRelacionedI.cardinalidadIMaxDomainPropertyId, typeof(EntidadReferencesRelacionedI.cardinalidadIMaxPropertyHandler)),
				new DomainMemberInfo(typeof(EntidadReferencesRelacionedD), "cardinalidadDMin", EntidadReferencesRelacionedD.cardinalidadDMinDomainPropertyId, typeof(EntidadReferencesRelacionedD.cardinalidadDMinPropertyHandler)),
				new DomainMemberInfo(typeof(EntidadReferencesRelacionedD), "cardinalidadDMax", EntidadReferencesRelacionedD.cardinalidadDMaxDomainPropertyId, typeof(EntidadReferencesRelacionedD.cardinalidadDMaxPropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(TapizHasEntidad), "Tapiz", TapizHasEntidad.TapizDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasEntidad), "Entidad", TapizHasEntidad.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadHasClave), "Entidad", EntidadHasClave.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadHasClave), "Clave", EntidadHasClave.ClaveDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadHasAtributoEntidad), "Entidad", EntidadHasAtributoEntidad.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadHasAtributoEntidad), "AtributoEntidad", EntidadHasAtributoEntidad.AtributoEntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadReferencesRelacionedI), "Entidad", EntidadReferencesRelacionedI.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadReferencesRelacionedI), "Relacion", EntidadReferencesRelacionedI.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionHasAtributoRelacioned), "Relacion", RelacionHasAtributoRelacioned.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionHasAtributoRelacioned), "AtributoRelacion", RelacionHasAtributoRelacioned.AtributoRelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadReferencesRelacionedD), "Entidad", EntidadReferencesRelacionedD.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadReferencesRelacionedD), "Relacion", EntidadReferencesRelacionedD.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasRelacioned), "Tapiz", TapizHasRelacioned.TapizDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasRelacioned), "Relacion", TapizHasRelacioned.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasEstiloGraficoPortalWebbed), "Tapiz", TapizHasEstiloGraficoPortalWebbed.TapizDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasEstiloGraficoPortalWebbed), "EstiloGraficoPortalWeb", TapizHasEstiloGraficoPortalWebbed.EstiloGraficoPortalWebDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasEstiloGraficoPaginaWebbed), "Tapiz", TapizHasEstiloGraficoPaginaWebbed.TapizDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasEstiloGraficoPaginaWebbed), "EstiloGraficoPaginaWeb", TapizHasEstiloGraficoPaginaWebbed.EstiloGraficoPaginaWebDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasEstiloGraficoCampoDeFormularios), "Tapiz", TapizHasEstiloGraficoCampoDeFormularios.TapizDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasEstiloGraficoCampoDeFormularios), "EstiloGraficoCampoDeFormulario", TapizHasEstiloGraficoCampoDeFormularios.EstiloGraficoCampoDeFormularioDomainRoleId),
				new DomainRolePlayerInfo(typeof(AtributoNormalHasRestriccioned), "AtributoNormal", AtributoNormalHasRestriccioned.AtributoNormalDomainRoleId),
				new DomainRolePlayerInfo(typeof(AtributoNormalHasRestriccioned), "Restriccion", AtributoNormalHasRestriccioned.RestriccionDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(27);
				createElementMap.Add(typeof(Tapiz), 0);
				createElementMap.Add(typeof(Entidad), 1);
				createElementMap.Add(typeof(Clave), 2);
				createElementMap.Add(typeof(AtributoEntidad), 3);
				createElementMap.Add(typeof(Relacion), 4);
				createElementMap.Add(typeof(AtributoRelacion), 5);
				createElementMap.Add(typeof(RestriccionRango), 6);
				createElementMap.Add(typeof(RestriccionEnum), 7);
				createElementMap.Add(typeof(EstiloGraficoPortalWeb), 8);
				createElementMap.Add(typeof(EstiloGraficoPaginaWeb), 9);
				createElementMap.Add(typeof(EstiloGraficoCampoDeFormulario), 10);
				createElementMap.Add(typeof(ANHAMMDRMLenguajeDiagram), 11);
				createElementMap.Add(typeof(ConectorDerecha), 12);
				createElementMap.Add(typeof(ConectorIzquierda), 13);
				createElementMap.Add(typeof(MetaforaEntidad), 14);
				createElementMap.Add(typeof(MetaforaClave), 15);
				createElementMap.Add(typeof(MetaforaAtributoE), 16);
				createElementMap.Add(typeof(MetaforaRelacion), 17);
				createElementMap.Add(typeof(MetaforaAtributoR), 18);
				createElementMap.Add(typeof(MetaforaRestriccionRango), 19);
				createElementMap.Add(typeof(MetaforaRestriccionEnum), 20);
				createElementMap.Add(typeof(MetaforaEGPortalWeb), 21);
				createElementMap.Add(typeof(MetaforaEGPaginaWeb), 22);
				createElementMap.Add(typeof(MetaforaEGCampoDeFormulario), 23);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new Tapiz(partition, propertyAssignments);
				case 1: return new Entidad(partition, propertyAssignments);
				case 2: return new Clave(partition, propertyAssignments);
				case 3: return new AtributoEntidad(partition, propertyAssignments);
				case 4: return new Relacion(partition, propertyAssignments);
				case 5: return new AtributoRelacion(partition, propertyAssignments);
				case 6: return new RestriccionRango(partition, propertyAssignments);
				case 7: return new RestriccionEnum(partition, propertyAssignments);
				case 8: return new EstiloGraficoPortalWeb(partition, propertyAssignments);
				case 9: return new EstiloGraficoPaginaWeb(partition, propertyAssignments);
				case 10: return new EstiloGraficoCampoDeFormulario(partition, propertyAssignments);
				case 11: return new ANHAMMDRMLenguajeDiagram(partition, propertyAssignments);
				case 12: return new ConectorDerecha(partition, propertyAssignments);
				case 13: return new ConectorIzquierda(partition, propertyAssignments);
				case 14: return new MetaforaEntidad(partition, propertyAssignments);
				case 15: return new MetaforaClave(partition, propertyAssignments);
				case 16: return new MetaforaAtributoE(partition, propertyAssignments);
				case 17: return new MetaforaRelacion(partition, propertyAssignments);
				case 18: return new MetaforaAtributoR(partition, propertyAssignments);
				case 19: return new MetaforaRestriccionRango(partition, propertyAssignments);
				case 20: return new MetaforaRestriccionEnum(partition, propertyAssignments);
				case 21: return new MetaforaEGPortalWeb(partition, propertyAssignments);
				case 22: return new MetaforaEGPaginaWeb(partition, propertyAssignments);
				case 23: return new MetaforaEGCampoDeFormulario(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(11);
				createElementLinkMap.Add(typeof(TapizHasEntidad), 0);
				createElementLinkMap.Add(typeof(EntidadHasClave), 1);
				createElementLinkMap.Add(typeof(EntidadHasAtributoEntidad), 2);
				createElementLinkMap.Add(typeof(EntidadReferencesRelacionedI), 3);
				createElementLinkMap.Add(typeof(RelacionHasAtributoRelacioned), 4);
				createElementLinkMap.Add(typeof(EntidadReferencesRelacionedD), 5);
				createElementLinkMap.Add(typeof(TapizHasRelacioned), 6);
				createElementLinkMap.Add(typeof(TapizHasEstiloGraficoPortalWebbed), 7);
				createElementLinkMap.Add(typeof(TapizHasEstiloGraficoPaginaWebbed), 8);
				createElementLinkMap.Add(typeof(TapizHasEstiloGraficoCampoDeFormularios), 9);
				createElementLinkMap.Add(typeof(AtributoNormalHasRestriccioned), 10);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new TapizHasEntidad(partition, roleAssignments, propertyAssignments);
				case 1: return new EntidadHasClave(partition, roleAssignments, propertyAssignments);
				case 2: return new EntidadHasAtributoEntidad(partition, roleAssignments, propertyAssignments);
				case 3: return new EntidadReferencesRelacionedI(partition, roleAssignments, propertyAssignments);
				case 4: return new RelacionHasAtributoRelacioned(partition, roleAssignments, propertyAssignments);
				case 5: return new EntidadReferencesRelacionedD(partition, roleAssignments, propertyAssignments);
				case 6: return new TapizHasRelacioned(partition, roleAssignments, propertyAssignments);
				case 7: return new TapizHasEstiloGraficoPortalWebbed(partition, roleAssignments, propertyAssignments);
				case 8: return new TapizHasEstiloGraficoPaginaWebbed(partition, roleAssignments, propertyAssignments);
				case 9: return new TapizHasEstiloGraficoCampoDeFormularios(partition, roleAssignments, propertyAssignments);
				case 10: return new AtributoNormalHasRestriccioned(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return ANHAMMDRMLenguajeDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (ANHAMMDRMLenguajeDomainModel.resourceManager == null)
				{
					ANHAMMDRMLenguajeDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(ANHAMMDRMLenguajeDomainModel).Assembly);
				}
				return ANHAMMDRMLenguajeDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return ANHAMMDRMLenguajeDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return ANHAMMDRMLenguajeDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (ANHAMMDRMLenguajeDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new ANHAMMDRMLenguajeCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					ANHAMMDRMLenguajeDomainModel.copyClosure = copyFilter;
				}
				return ANHAMMDRMLenguajeDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (ANHAMMDRMLenguajeDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new ANHAMMDRMLenguajeDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					ANHAMMDRMLenguajeDomainModel.removeClosure = removeFilter;
				}
				return ANHAMMDRMLenguajeDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.DecoratorPropertyChanged));
			ruleManager.EnableRule(typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ConnectorRolePlayerChanged));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.DecoratorPropertyChanged));
			ruleManager.DisableRule(typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ConnectorRolePlayerChanged));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class ANHAMMDRMLenguajeDeleteClosure : ANHAMMDRMLenguajeDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public ANHAMMDRMLenguajeDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class ANHAMMDRMLenguajeDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public ANHAMMDRMLenguajeDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TapizHasEntidad.EntidadDomainRoleId, true);
			DomainRoles.Add(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EntidadHasClave.ClaveDomainRoleId, true);
			DomainRoles.Add(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EntidadHasAtributoEntidad.AtributoEntidadDomainRoleId, true);
			DomainRoles.Add(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.RelacionHasAtributoRelacioned.AtributoRelacionDomainRoleId, true);
			DomainRoles.Add(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TapizHasRelacioned.RelacionDomainRoleId, true);
			DomainRoles.Add(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TapizHasEstiloGraficoPortalWebbed.EstiloGraficoPortalWebDomainRoleId, true);
			DomainRoles.Add(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TapizHasEstiloGraficoPaginaWebbed.EstiloGraficoPaginaWebDomainRoleId, true);
			DomainRoles.Add(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TapizHasEstiloGraficoCampoDeFormularios.EstiloGraficoCampoDeFormularioDomainRoleId, true);
			DomainRoles.Add(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.AtributoNormalHasRestriccioned.RestriccionDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class ANHAMMDRMLenguajeCopyClosure : ANHAMMDRMLenguajeCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public ANHAMMDRMLenguajeCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class ANHAMMDRMLenguajeCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public ANHAMMDRMLenguajeCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}
namespace IPS.ANHAMMDRM.ANHAMMDRMLenguaje
{
	/// <summary>
	/// DomainEnumeration: TiposCardinalidad
	/// Description for IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TiposCardinalidad
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TiposCardinalidad
	{
		/// <summary>
		/// Cero
		/// Description for IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TiposCardinalidad.Cero
		/// </summary>
		[DslDesign::DescriptionResource("IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TiposCardinalidad/Cero.Description", typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDomainModel), "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.GeneratedCode.DomainModelResx")]
		Cero = 0,
		/// <summary>
		/// Uno
		/// Description for IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TiposCardinalidad.Uno
		/// </summary>
		[DslDesign::DescriptionResource("IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TiposCardinalidad/Uno.Description", typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDomainModel), "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.GeneratedCode.DomainModelResx")]
		Uno = 1,
		/// <summary>
		/// N
		/// Description for IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TiposCardinalidad.N
		/// </summary>
		[DslDesign::DescriptionResource("IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TiposCardinalidad/N.Description", typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDomainModel), "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.GeneratedCode.DomainModelResx")]
		N = 2,
	}
}
namespace IPS.ANHAMMDRM.ANHAMMDRMLenguaje
{
	/// <summary>
	/// DomainEnumeration: TipoFormatoDeVisualizacion
	/// Description for IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TipoFormatoDeVisualizacion
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TipoFormatoDeVisualizacion
	{
		/// <summary>
		/// AreaDeTexto
		/// Description for
		/// IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TipoFormatoDeVisualizacion.AreaDeTexto
		/// </summary>
		[DslDesign::DescriptionResource("IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TipoFormatoDeVisualizacion/AreaDeTexto.Description", typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDomainModel), "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.GeneratedCode.DomainModelResx")]
		AreaDeTexto,
		/// <summary>
		/// CheckBox
		/// Description for
		/// IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TipoFormatoDeVisualizacion.CheckBox
		/// </summary>
		[DslDesign::DescriptionResource("IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TipoFormatoDeVisualizacion/CheckBox.Description", typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDomainModel), "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.GeneratedCode.DomainModelResx")]
		CheckBox,
		/// <summary>
		/// RadioButton
		/// Description for
		/// IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TipoFormatoDeVisualizacion.RadioButton
		/// </summary>
		[DslDesign::DescriptionResource("IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TipoFormatoDeVisualizacion/RadioButton.Description", typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDomainModel), "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.GeneratedCode.DomainModelResx")]
		RadioButton,
		/// <summary>
		/// ListaDesplegable
		/// Description for
		/// IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TipoFormatoDeVisualizacion.ListaDesplegable
		/// </summary>
		[DslDesign::DescriptionResource("IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TipoFormatoDeVisualizacion/ListaDesplegable.Description", typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDomainModel), "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.GeneratedCode.DomainModelResx")]
		ListaDesplegable,
	}
}
namespace IPS.ANHAMMDRM.ANHAMMDRMLenguaje
{
	/// <summary>
	/// DomainEnumeration: TiposDeDatos
	/// Description for IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TiposDeDatos
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TiposDeDatos
	{
		/// <summary>
		/// Entero
		/// Description for IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TiposDeDatos.Entero
		/// </summary>
		[DslDesign::DescriptionResource("IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TiposDeDatos/Entero.Description", typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDomainModel), "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.GeneratedCode.DomainModelResx")]
		Entero,
		/// <summary>
		/// Real
		/// Description for IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TiposDeDatos.Real
		/// </summary>
		[DslDesign::DescriptionResource("IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TiposDeDatos/Real.Description", typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDomainModel), "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.GeneratedCode.DomainModelResx")]
		Real,
		/// <summary>
		/// Fecha
		/// Description for IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TiposDeDatos.Fecha
		/// </summary>
		[DslDesign::DescriptionResource("IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TiposDeDatos/Fecha.Description", typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDomainModel), "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.GeneratedCode.DomainModelResx")]
		Fecha,
		/// <summary>
		/// Alfanumerico
		/// Description for IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TiposDeDatos.Alfanumerico
		/// </summary>
		[DslDesign::DescriptionResource("IPS.ANHAMMDRM.ANHAMMDRMLenguaje.TiposDeDatos/Alfanumerico.Description", typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDomainModel), "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.GeneratedCode.DomainModelResx")]
		Alfanumerico,
	}
}

