//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Windows.Forms;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

namespace IPS.ANHAMMDRM.ANHAMMDRMLenguaje
{
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	/// <remarks>
	/// Double-derived class to allow easier code customization.
	/// </remarks>
	public partial class ANHAMMDRMLenguajeToolboxHelper : ANHAMMDRMLenguajeToolboxHelperBase 
	{
		/// <summary>
		/// Constructs a new ANHAMMDRMLenguajeToolboxHelper.
		/// </summary>
		public ANHAMMDRMLenguajeToolboxHelper(global::System.IServiceProvider serviceProvider)
			: base(serviceProvider) { }
	}
	
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable", Justification = "The store is disposed on domain shut down")]
	public abstract class ANHAMMDRMLenguajeToolboxHelperBase
	{
		/// <summary>
		/// Toolbox item filter string used to identify ANHAMMDRMLenguaje toolbox items.  
		/// </summary>
		/// <remarks>
		/// See the MSDN documentation for the ToolboxItemFilterAttribute class for more information on toolbox
		/// item filters.
		/// </remarks>
		public const string ToolboxFilterString = "ANHAMMDRMLenguaje.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify ConectorDerecha connector tool.
		/// </summary>
		public const string ConectorDerechaFilterString = "ConectorDerecha.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify ConectorIzquierda connector tool.
		/// </summary>
		public const string ConectorIzquierdaFilterString = "ConectorIzquierda.1.0";

	
		private global::System.Collections.Generic.Dictionary<string, DslDesign::ModelingToolboxItem> toolboxItemCache = new global::System.Collections.Generic.Dictionary<string, DslDesign::ModelingToolboxItem>();
		private DslModeling::Store toolboxStore;
		
		private global::System.IServiceProvider sp;
		
		/// <summary>
		/// Constructs a new ANHAMMDRMLenguajeToolboxHelperBase.
		/// </summary>
		protected ANHAMMDRMLenguajeToolboxHelperBase(global::System.IServiceProvider serviceProvider)
		{
			if(serviceProvider == null) throw new global::System.ArgumentNullException("serviceProvider");
			
			this.sp = serviceProvider;
		}
		
		/// <summary>
		/// Serivce provider used to access services from the hosting environment.
		/// </summary>
		protected global::System.IServiceProvider ServiceProvider
		{
			get
			{
				return this.sp;
			}
		}

		/// <summary>
		/// Returns the display name of the tab that should be opened by default when the editor is opened.
		/// </summary>
		public static string DefaultToolboxTabName
		{
			get
			{
				return global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDomainModel.SingletonResourceManager.GetString("ANHAMMDRMLenguajeToolboxTab", global::System.Globalization.CultureInfo.CurrentUICulture);
			}
		}
		
		
		/// <summary>
		/// Returns the toolbox items count in the default tool box tab.
		/// </summary>
		public static int DefaultToolboxTabToolboxItemsCount
		{
			get
			{
				return 10;
			}
		}
		

		/// <summary>
		/// Returns a list of custom toolbox items to be added dynamically
		/// </summary>
		public virtual global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem> toolboxItems = new global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem>();
			return toolboxItems;
		}
		
		/// <summary>
		/// Creates an ElementGroupPrototype for the element tool corresponding to the given domain class id.
		/// Default behavior is to create a prototype containing an instance of the domain class.
		/// Derived classes may override this to add additional information to the prototype.
		/// </summary>
		protected virtual DslModeling::ElementGroupPrototype CreateElementToolPrototype(DslModeling::Store store, global::System.Guid domainClassId)
		{
			DslModeling::ModelElement element = store.ElementFactory.CreateElement(domainClassId);
			DslModeling::ElementGroup elementGroup = new DslModeling::ElementGroup(store.DefaultPartition);
			elementGroup.AddGraph(element, true);
			return elementGroup.CreatePrototype();
		}

		/// <summary>
		/// Returns instance of ModelingToolboxItem based on specified name.
		/// This method must be called from within a Transaction. Failure to do so will result in an exception
		/// </summary>
		/// <param name="itemId">unique name of desired ToolboxItem</param>
		/// <param name="store">Store to perform the operation against</param>
		/// <returns>An instance of ModelingToolboxItem if the itemId can be resolved, null otherwise</returns>
		public virtual DslDesign::ModelingToolboxItem GetToolboxItem(string itemId, DslModeling::Store store)
		{
			DslDesign::ModelingToolboxItem result = null;
			if (string.IsNullOrEmpty(itemId))
			{
				return null;
			}
			if (store == null)
			{
				return null;
			}
			global::System.Resources.ResourceManager resourceManager = global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDomainModel.SingletonResourceManager;
			global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;
			switch(itemId)
			{
				case "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EntidadToolboxItem":
					// Add Entidad shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EntidadToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EntidadToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EntidadToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ANHAMMDRMLenguajeToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Entidad", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EntidadToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Entidad.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ClaveToolboxItem":
					// Add Clave shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ClaveToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ClaveToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ClaveToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ANHAMMDRMLenguajeToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Clave", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ClaveToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Clave.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.AtributoEToolboxItem":
					// Add AtributoE shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.AtributoEToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						3, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("AtributoEToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("AtributoEToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ANHAMMDRMLenguajeToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"AtributoE", // F1 help keyword for the toolbox item.
						resourceManager.GetString("AtributoEToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.AtributoEntidad.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.RelacionToolboxItem":
					// Add Relacion shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.RelacionToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						4, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("RelacionToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("RelacionToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ANHAMMDRMLenguajeToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Relacion", // F1 help keyword for the toolbox item.
						resourceManager.GetString("RelacionToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.Relacion.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.AtributoRToolboxItem":
					// Add AtributoR shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.AtributoRToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						5, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("AtributoRToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("AtributoRToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ANHAMMDRMLenguajeToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"AtributoR", // F1 help keyword for the toolbox item.
						resourceManager.GetString("AtributoRToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.AtributoRelacion.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.RestriccionRangoToolboxItem":
					// Add RestriccionRango shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.RestriccionRangoToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						6, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("RestriccionRangoToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("RestriccionRangoToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ANHAMMDRMLenguajeToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"RestriccionRango", // F1 help keyword for the toolbox item.
						resourceManager.GetString("RestriccionRangoToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.RestriccionRango.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.RestriccionEnumToolboxItem":
					// Add RestriccionEnum shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.RestriccionEnumToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						7, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("RestriccionEnumToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("RestriccionEnumToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ANHAMMDRMLenguajeToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"RestriccionEnum", // F1 help keyword for the toolbox item.
						resourceManager.GetString("RestriccionEnumToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.RestriccionEnum.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGrafPortalWebToolToolboxItem":
					// Add EstiloGrafPortalWebTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGrafPortalWebToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						8, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EstiloGrafPortalWebToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EstiloGrafPortalWebToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ANHAMMDRMLenguajeToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"EstiloGrafPortalWebTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EstiloGrafPortalWebToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoPortalWeb.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGráficoPaginaWebToolToolboxItem":
					// Add EstiloGráficoPaginaWebTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGráficoPaginaWebToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						9, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EstiloGráficoPaginaWebToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EstiloGráficoPaginaWebToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ANHAMMDRMLenguajeToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"EstiloGráficoPaginaWebTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EstiloGráficoPaginaWebToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoPaginaWeb.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoCampoDeFormularioToolToolboxItem":
					// Add EstiloGraficoCampoDeFormularioTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoCampoDeFormularioToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						10, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EstiloGraficoCampoDeFormularioToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EstiloGraficoCampoDeFormularioToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ANHAMMDRMLenguajeToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"EstiloGraficoCampoDeFormularioTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EstiloGraficoCampoDeFormularioToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.EstiloGraficoCampoDeFormulario.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ConectorDerechaToolboxItem":

					// Add ConectorDerecha connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ConectorDerechaToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ConectorDerechaToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ConectorDerechaToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeConectoresToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ANHAMMDRMLenguajeConectoresToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ConectorDerecha", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ConectorDerechaToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ConectorDerechaFilterString)
						});
					break;
				case "IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ConectorIzquierdaToolboxItem":

					// Add ConectorIzquierda connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ConectorIzquierdaToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ConectorIzquierdaToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ConectorIzquierdaToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeConectoresToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("ANHAMMDRMLenguajeConectoresToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ConectorIzquierda", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ConectorIzquierdaToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ConectorIzquierdaFilterString)
						});
					break;
				default:
					break;
			} // end switch
			
			return result;
		}
		

		/// <summary>
		/// The store toe be used for all the toolbox item creation
		/// </summary>
		protected DslModeling::Store ToolboxStore
		{
			get
			{ 
				if (toolboxStore==null)
				{
					toolboxStore = new DslModeling::Store(this.ServiceProvider);
					EventHandler StoreCleanUp = (o, e) =>
					{
						//Since Store implements IDisposable, we need to dispose it when we're finished
						if (this.toolboxStore != null)
						{
							this.toolboxStore.Dispose();
						}
						this.toolboxStore = null;
					};
					//There is no DomainUnload event for the default AppDomain, so we listen for both ProcessExit and DomainUnload
					AppDomain.CurrentDomain.ProcessExit += new EventHandler(StoreCleanUp);
					AppDomain.CurrentDomain.DomainUnload += new EventHandler(StoreCleanUp);
					
					//load the domain model
					toolboxStore.LoadDomainModels(typeof(global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDomainModel));
					
				}
				return toolboxStore;
			}
		}
		
		/// <summary>
		/// Given a toolbox item "unique ID" returns the the toolbox item using cached dictionary
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve</param>
		private DslDesign::ModelingToolboxItem GetToolboxItem(string itemId)
		{
			DslDesign::ModelingToolboxItem item = null;

			if (!this.toolboxItemCache.TryGetValue(itemId, out item))
			{
				DslModeling::Store store = this.ToolboxStore;
				
				// Open transaction so we can create model elements corresponding to toolbox items.
				using (DslModeling::Transaction t = store.TransactionManager.BeginTransaction("CreateToolboxItems"))
				{
					// Retrieve the specified ToolboxItem from the DSL
					this.toolboxItemCache[itemId] = item = this.GetToolboxItem(itemId, store);
				}
			}

			return item;
		}
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		public virtual object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			DslDesign::ModelingToolboxItem item = null;

			global::System.Resources.ResourceManager resourceManager = global::IPS.ANHAMMDRM.ANHAMMDRMLenguaje.ANHAMMDRMLenguajeDomainModel.SingletonResourceManager;
			global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;

			System.Windows.Forms.IDataObject tbxDataObj;

			//get the toolbox item
			item = GetToolboxItem(itemId);

			if (item != null)
			{
				ToolboxItemContainer container = new ToolboxItemContainer(item);
				tbxDataObj = container.ToolboxData;

				if (tbxDataObj.GetDataPresent(format.Name))
				{
					return tbxDataObj.GetData(format.Name);
				}
				else 
				{
					string invalidFormatString = resourceManager.GetString("UnsupportedToolboxFormat", resourceCulture);
					throw new InvalidOperationException(string.Format(resourceCulture, invalidFormatString, format.Name));
				}
			}

			string errorFormatString = resourceManager.GetString("UnresolvedToolboxItem", resourceCulture);
			throw new InvalidOperationException(string.Format(resourceCulture, errorFormatString, itemId));
		}		
	}
}
